version: "3"

services:
  emily-tumor-segmentation-s753o9:

    image: emily-tumor-segmentation-s753o9-dev
    container_name: emily-tumor-segmentation-s753o9-dev

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-tumor-segmentation-s753o9-dev-network
    
    
networks:
  emily-tumor-segmentation-s753o9-dev-network:
    driver: bridge
    name: emily-tumor-segmentation-s753o9-dev-network