version: "3"

services:
  emily-lunar-lander-nkj4rs:

    image: emily-lunar-lander-nkj4rs-dev
    container_name: emily-lunar-lander-nkj4rs-dev

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-lunar-lander-nkj4rs-dev-network
    
    
networks:
  emily-lunar-lander-nkj4rs-dev-network:
    driver: bridge
    name: emily-lunar-lander-nkj4rs-dev-network