version: "3"

services:
  emily-ai-text-detector-ob9m2n:

    image: emily-ai-text-detector-ob9m2n-dev
    container_name: emily-ai-text-detector-ob9m2n-dev

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-ai-text-detector-ob9m2n-dev-network
    
    
networks:
  emily-ai-text-detector-ob9m2n-dev-network:
    driver: bridge
    name: emily-ai-text-detector-ob9m2n-dev-network